"""Sync schema updates

Revision ID: dd53c58fca1d
Revises: 
Create Date: 2026-05-29 14:31:32.680139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd53c58fca1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('klaim', sa.Column('owner_name', sa.String(length=255), nullable=True))
    op.add_column('klaim', sa.Column('nim', sa.String(length=50), nullable=True))
    op.add_column('klaim', sa.Column('faculty', sa.String(length=255), nullable=True))
    op.add_column('klaim', sa.Column('contact', sa.String(length=255), nullable=True))
    op.alter_column('laporan', 'deskripsi',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('laporan', 'ciri_ciri')
    # Preserve data by renaming columns instead of dropping
    op.alter_column('users', 'nama', new_column_name='name')
    op.alter_column('users', 'email_ipb', new_column_name='email')
    op.alter_column('users', 'nomor_telepon', new_column_name='phone')
    op.add_column('users', sa.Column('nim', sa.String(length=50), server_default='000000', nullable=False))
    op.drop_index('ix_users_email_ipb', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name', new_column_name='nama')
    op.alter_column('users', 'email', new_column_name='email_ipb')
    op.alter_column('users', 'phone', new_column_name='nomor_telepon')
    op.drop_column('users', 'nim')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email_ipb', 'users', ['email_ipb'], unique=True)
    op.add_column('laporan', sa.Column('ciri_ciri', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('laporan', 'deskripsi',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('klaim', 'contact')
    op.drop_column('klaim', 'faculty')
    op.drop_column('klaim', 'nim')
    op.drop_column('klaim', 'owner_name')
    # ### end Alembic commands ###
